language: c

# Install criterion library
before_install:
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get update -q
    - sudo apt-get install criterion-dev -y

jobs: 
    include:
        # Set up various jobs here. Anything with dependencies must be in the same job

        # Make and run tests
        - stage: test
          script: make tests && ./tests/test-spellcheck