language: c

before_install:
    - git submodule update --init --recursive
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get update -q
    - sudo apt-get install criterion-dev -y
    - git clone https://github.com/redis/hiredis.git
    - cd hiredis
    - make
    - sudo make install
    - sudo ldconfig
    - cd ..

jobs:
    include:
        - stage: make
          script: make
          script: make tests

        - stage: test
          script: 
            - make tests
            - ./tests/test-spellcheck

        - stage: quiet
          script: 
            - make 
            - ./spellcheck 0.txt -q -s test_result.txt -vvv

        - stage: interactive 1
          script: 
            - make 
            - ./spellcheck < tests/test_main0.txt

        - stage: verbose 1
          script: 
            - make 
            - ./spellcheck < tests/test_main1.txt

        - stage: verbose 2
          script: 
            - make 
            - ./spellcheck 0.txt -l