language: c

before_install:
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get update -q
    - sudo apt-get install criterion-dev -y

script:
    - make tests
    - ./tests/test-spellcheck
    - make
    - ./spellcheck -v tests/test_short.txt -s test1.txt
    - ./spellcheck -q tests/test_short.txt -s test2.txt
    - ./spellcheck < test_main0.txt
    - ./spellcheck < test_main1.txt
    - make clean
