language: c

before_install:
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get -y update
    - sudo apt-get -y install criterion-dev

script:
    - make tests
    - ./tests/test-spellcheck